Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,4 +1,4 @@
-name: Release Versioning
+name: Version and Release
 
 on:
   push:
@@ -13,33 +13,35 @@ jobs:
         id: version
         run: |
           TAG_PREFIX="v"
-          CURRENT_VERSION=$(cat version.txt)
-          echo "Current version: $CURRENT_VERSION"
-          
+          if [ -f version.txt ]; then
+            CURRENT_VERSION=$(cat version.txt)
+            echo "Current version: $CURRENT_VERSION"
+          else
+            echo "Version file not found. Exiting."
+            exit 1
+          fi
+
       - name: Increment version
         run: |
-          # Assuming your version follows the semantic versioning format (major.minor.patch)
           IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
           MAJOR="${VERSION_PARTS[0]}"
           MINOR="${VERSION_PARTS[1]}"
           PATCH="${VERSION_PARTS[2]}"
-          
+
           # Increment the minor version (you can adjust this based on your versioning strategy)
           MINOR=$((MINOR + 1))
-          
+
           # Construct the new version
           NEW_VERSION="$MAJOR.$MINOR.$PATCH"
           echo "New version: $NEW_VERSION"
-          
+
           # Save the new version to the file
           echo "$NEW_VERSION" > version.txt
-          
+
       - name: Set version and release
         run: |
           TAG_PREFIX="v"
           RELEASE_VERSION=$(cat version.txt)
-          RELEASE_INFO="{\"version\": \"$TAG_PREFIX$RELEASE_VERSION\", \"sha\": \"$GITHUB_SHA\"}"
+          RELEASE_INFO="{\"version\": \"$TAG_PREFIX$RELEASE_VERSION\"}"
           echo "Release version: $TAG_PREFIX$RELEASE_VERSION"
           echo "Release info in JSON format: $RELEASE_INFO"
-
-
